######
#
# For testing xinterp
#
######

test:: \
test_output

######

test_output:: ; \
$(MAKE) -f Makefile_output

######
#
# HX: for cleaning up
#
######
clean:: ; rm -f *~
######
cleanall:: clean
cleanall:: ; rm -f output
######

###### end of [Makefile] ######
